# Generated by Django 3.1.2 on 2021-01-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210114_1953'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_return',
        ),
    ]
