# Generated by Django 3.1.2 on 2021-01-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_tbl_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=30)),
                ('cust_id', models.CharField(max_length=30)),
                ('prod_id', models.CharField(max_length=30)),
                ('prod_qty', models.FloatField()),
                ('prod_amt', models.FloatField()),
                ('return_cat', models.CharField(max_length=30)),
                ('return_status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_return',
            },
        ),
    ]
