# Generated by Django 3.1.2 on 2021-01-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_tbl_return_return_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_return',
            old_name='prod_amt',
            new_name='order_amt',
        ),
        migrations.RenameField(
            model_name='tbl_return',
            old_name='prod_id',
            new_name='order_id',
        ),
        migrations.RemoveField(
            model_name='tbl_return',
            name='prod_qty',
        ),
    ]
