# Generated by Django 3.1.2 on 2021-01-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210117_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_customer',
            name='cust_status',
        ),
    ]
