# Generated by Django 3.1.2 on 2021-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_tbl_review_cust_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='cust_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
