# Generated by Django 3.1.2 on 2021-01-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_tbl_complaint_cust_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_order',
            name='order_paymode',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
