# Generated by Django 3.1.2 on 2021-01-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_tbl_order_order_paymode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='prod_rol',
            field=models.FloatField(),
        ),
    ]
